on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run action locally
        uses: ./ # Uses an action in the root directory
        id: hello
        with:
          name: 'Rust'
